### PR TITLE
add docker setup

### PR DESCRIPTION
**Pull request by samsonasu**
also stop using puma because it's multithreading messes with me

### CODE REVIEW

**Comment by deploybot2000** [comment]
NO PIVOTAL CASES DETECTORED

**Comment by petitJAM** [comment]
:ship: 

I would prefer if that were 2 commits, one with docker and one with the puma removal (and why it was removed). I think it would be nice for apprentices to be able to read through the commit history to see how the project got to where it is. 

My initial commits are pretty well divided and explained I think.

I mean, this could maybe still be one commit if the puma removal is important to make docker work, but I'd like that to be in the commit message.

**Comment by samsonasu** [comment]
It's important to remove because on windows docker has a bug where because of windows permissions it can't open the same file more than once, which puma tries to do with `development.db`

**Comment by samsonasu** [comment]
good to know about the commits though

**Pull request merged**
